name: 'Duke Nukem'

on:
  workflow_dispatch:
  workflow_call:
permissions:
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  plan:
    strategy: 
      matrix: 
        env: [dev]
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: aks-simple

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Terraform Destroy
      run: |
        terraform init -backend-config=key=${{ matrix.env  }}.tfvars
        terraform destroy -var-file=env/${{ matrix.env  }}.tfvars -auto-approve
