name: 'Terraform'

on: 
  workflow_dispatch:
  workflow_call:
permissions:
  contents: read
  issues: write
  pull-requests: write

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  plan:
    strategy: 
      matrix: 
        env: [dev]
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: aks-simple

    steps:
    - uses: actions/checkout@v3
      with:
        repository: lambergluke/aks-resume-cluster

    - name: Terraform Plan
      run: |
        terraform init -backend-config=key=${{ matrix.env  }}.tfvars
        terraform plan -input=false -var-file=env/${{ matrix.env  }}.tfvars -out tfplan 
        
    - name: Terraform Apply
      run: |
        terraform apply -input=false tfplan
