name: 'Terraform'

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Terraform Plan
      run: |
        terraform init
        terraform plan -input=false -out=tfplan
    - name: Upload Plan Artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3.0.0
      with:
        name: tfplan
        path: tfplan
    
  apply:
    needs: plan
    if: github.ref == 'refs/heads/main'
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download Plan Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: tfplan
        path: .

    - name: Terraform Apply
      run: |
        terraform init
        terraform apply -input=false tfplan
